### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/sample-data#1]
* date, enum, integer and number fields should not have `""` or `"None"` as value
* number fields shouldn't have strings like `"37310290"` as values
* date fields shouldn't have values like `2014-01-15 14:00 Eastern Standard Time (EST)`
* isAmendment should be boolean not `""`, `"0"`, `"1"`, `"2"`, ..., `"T01"`, etc.
* Invalid method: `Traditional Competitive`, `Traditional Non-Competitive`, `Open Bidding`, etc.
* Invalid selectionCriteria: `Subsequent/Follow-on Contracts`, `Exclusive Rights`, etc.

**Comment by timgdavies** [comment]
As BuyAndSell.gc.ca are now producing their own data, I've moved their data to an archived branch, and will start building out a new collection of sample data here.
