### ISSUE TITLE
versionedRelease does not validate in record

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/sample-data#10]
The releases now validate https://github.com/open-contracting/sample-data/pull/3 , and as of https://github.com/open-contracting/sample-data/pull/5 the record will validate if the `versionedRelease` is removed, so the remaining step is to ensure this part validates.

**Comment by jpmckinney** [comment]
This seems to be closed, but if there are still validation issues, they will be picked up in https://github.com/open-contracting/standard-maintenance-scripts/issues/7
