### ISSUE TITLE
Check for fields in the example that aren't in the schema

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/sample-data#11]
The dev Cove site now exposes the list of extra fields in a file that aren't in the schema. I've just checked the sample releases files, and https://github.com/open-contracting/sample-data/issues/4 is the only issue atm.

* [ ] Once this is fixed it would be good to set up a travis test to check for such fields.

(See also https://github.com/open-contracting/sample-data/issues/7 which covers the opposite way round - fields in the schema but not the sample).

**Comment by jpmckinney** [comment]
Closing for same reason as #42.
