### ISSUE TITLE
Sample file no longer validates

### ISSUE THREAD

**Issue by ekoner** [open-contracting/sample-data#14]
This file https://raw.githubusercontent.com/open-contracting/sample-data/master/fictional-example/ocds-213czf-000-00001-02-tender.json no longer validates against the schema due to incorrect date format: http://cove.opendataservices.coop/ocds/data/33eef3b7-8083-4e41-9394-4e112f3fcf2b

**Comment by ekoner** [comment]
I've added a fixed verision here: https://www.dropbox.com/s/t9igocc887lxber/ocds-213czf-000-00001-02-tender.json?raw=1

**Comment by timgdavies** [comment]
Thanks for flagging this Edafe. I've just been through and added sensible dates to everything on a branch, and just waiting for it to be merged.

For the meantime, [fixed files are here](https://github.com/open-contracting/sample-data/tree/14-fix-dates/fictional-example).

**Comment by Bjwebb** [comment]
This is related to https://github.com/open-contracting/sample-data/issues/8

**Comment by Bjwebb** [comment]
Additionally, we should make sure the automated tests of the sample data are checking the dates, I've opened a new issue for this https://github.com/open-contracting/sample-data/issues/16

**Comment by timgdavies** [comment]
(Sorry about the extra commits. Tried a rebase but didn't quite get it right)
