### ISSUE TITLE
Validate that the dates are correct in automated tests of our sample data

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/sample-data#16]
We should be able to update the tests to validate that the dates are correct.

**Comment by jpmckinney** [comment]
I believe validate.sh does this. If not, it will be handled in https://github.com/open-contracting/standard-maintenance-scripts/issues/7

**Comment by Bjwebb** [comment]
validate.sh doesn't do this, see https://github.com/open-contracting/standard-maintenance-scripts/issues/7#issuecomment-333163950
