### ISSUE TITLE
Data in bigQuery includes all many columns which are null

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/sample-data#31]
The data loaded into BigQuery from the etl-prototype branch includes all fields in the OCDS schema, even where there is no data for a field. This means there are lots of columns in the datasets where all the values are NULL which makes the data hard to work with.

Ideally the bigQuery load process would result in 3 sets of release/record datsets for each publisher:

**core schema - data only**
Including only the fields/columns for which a value is provided in at least one release/record.

**core schema - all fields**
Including all columns in the core OCDS schema to support analysis of a standard table structure across multiple datasets/pubishers

**extensions**
Including only fields not in the core schema + the ocid and release id so this can be joined with the other tables

**Comment by annapowellsmith** [comment]
Thanks for the feedback. In what way does it make the data hard to work with?

If the problem is that the results include a lot of null values and the files are large as a result, then it may be easier to restrict the query (i.e. `SELECT field1, field2 FROM...` instead of `SELECT * FROM...`), rather than to create new datasets for each publisher.

**Comment by duncandewhurst** [comment]
Hi Anna,

Yes that's the issue, the results are large in terms of columns and I don't know how to simply return just the columns with data, though I'm certainly no SQL expert.

For example, I wanted to check how what values had changed between releases for the same `ocid` in the `australia_nsw` table.

So I used the following query to extra data from the `australia_nsw` table where there are multiple releases per `ocid`:

```SQL
SELECT * FROM ocds-172716.releases.australia_nsw
WHERE ocid IN (
SELECT ocid FROM ocds-172716.releases.australia_nsw
GROUP BY ocid
HAVING count(id) > 1 )
ORDER BY ocid, date ASC
```
This returns a table with few rows but many columns, the values for most of which are all `NULL` which makes it hard to see which values are being used/changed.

Since there are so many columns in the dataset my SQL skills fall down on how to quickly identify which columns to include in the `SELECT` statement so I thought a separate dataset might make this easier for users of a similar skill level.

Thanks!

**Comment by vicktoh** [comment]
I think you have a modeling problem here, SQL databases are optimized for storing complete data-sets, you may consider storing only the most important field in the SQL database and store the full releases as json documents.
As for your problem of finding how and what values have changed try loading each release in memory as an object or associative array,depending on the programming language your using you can perform some set operations on the objects to find the difference between the fields

**Comment by jpmckinney** [comment]
Superseded by new ETL work.
