### ISSUE TITLE
update_to_v1.1 script doesn't handle amendments

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/sample-data#32]
The [update_to_v1.1 script](https://github.com/open-contracting/sample-data/blob/etl-prototype/real-examples/update_to_v1_1.py) in the etl-prototype branch doesn't convert amendments to the new approach used in 1.1

**Comment by timgdavies** [comment]
@duncandewhurst Is there any chance you could have a first glance at this?

**Comment by duncandewhurst** [comment]
@timgdavies will do

**Comment by duncandewhurst** [comment]
See https://github.com/open-contracting/sample-data/pull/33

Currently this doesn't throw away any data in ```amendment```, it just copies ```amendment.date``` and ```amendment.rationale``` into a new entry in the ```amendments``` array

To 'upgrade' the structured information on changed fields in the ```amendment.changes``` array would mean creating a new release with the old values, to refer to in ```amendments.amendsReleaseID```. I'm not sure we want to do that?

**Comment by jpmckinney** [comment]
#33 is merged. I'm not sure we want to/can correctly create new releases with old values (things like release `id` and `tag` will need to be invented), so closing - but can re-open if there is disagreement.
