### ISSUE TITLE
Publisher fields are not populated correctly

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/sample-data#4]
In https://github.com/open-contracting/sample-data/commit/17d1d6308c737b2c82d38dd6a3da0343dda7ec53 I've updated `legalName` to `name`, in order to make the files validate. However, I also note that `id` should be `uid`.

The publisher block seems oddly inconsistent with Identifier bugs? Is this deliberate, or possibly a standard bug?

**Comment by timgdavies** [comment]
I don't think this was deliberate - I think this is probably a bug down to a lack of focus on the Release Package when we were finalising 1.0RC. 

Worth filing as an issue against the standard to see if we should change it (backwards incompatible) or leave it.

**Comment by Bjwebb** [comment]
Thanks, I've reported an issue against the standard https://github.com/open-contracting/standard/issues/245

Leaving this issue open, because the sample-data should be changed to reflect the current standard - ie. to use `uid` in the publisher data.

**Comment by jpmckinney** [comment]
Re: last comment, sample-data will need to be updated for each new version of the standard, so closing as otherwise this is a perpetually open issue.
