### ISSUE TITLE
Document how sample data is created and managed

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/sample-data#42]
The creation and management of the files under `real-examples` is documented at https://github.com/open-contracting/sample-data/tree/master/real-examples, but the other files are not similarly documented.

**Comment by timgdavies** [comment]
Self assigning: will pick up in a few weeks.

**Comment by jpmckinney** [comment]
I copied over the explanations for fictional-examples from the CRM.

**Comment by jpmckinney** [comment]
Closing in favor of a broader discussion of what to do with / how to maintain this repository going forward (of which #72 is part).
