### ISSUE TITLE
Make comprehensive use of OCDS fields in fictional-data examples

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/sample-data#7]
This kind of a check may be useful to implement in Cove https://github.com/OpenDataServices/cove/issues/118 or there may be a quicker short term way to do this.

**Comment by Bjwebb** [comment]
This has been implemented in Cove, but isn't exposed through the API, because it's difficult to know how to display.

I should be able to write a short python script to pull the raw data out, and calculate what we want to know here - this may require some changes to Cove, but this is something our radar to make possible anyway https://github.com/OpenDataServices/cove/issues/207

**Comment by jpmckinney** [comment]
This issue seems to be superseded by the linked CoVE issues.

**Comment by jpmckinney** [comment]
Nevermind, understood issue. Renaming it.

**Comment by jpmckinney** [comment]
Closing for same reason as #42.
