### ISSUE TITLE
Delete fetchers from here that are now in ocdsdata, move READMEs to heredocs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/sample-data#71]
To avoid confusion, we should delete all fetch.py from here that have been moved to ocdsdata.

If there is useful content in a source's README.md, we should move that to a heredoc in the scraper in ocdsdata, and delete the README here.

**Comment by jpmckinney** [comment]
@robredpath Could this be added to (discussed as part of) the current sprint?

**Comment by robredpath** [comment]
@jpmckinney It could, but it feels less important than most (if not all) of the tasks currently in the backlog and it doesn't help us satisfy the main user story that we're trying to target with the ETL work. Is there a cost associated with delaying this work?

**Comment by jpmckinney** [comment]
We can certainly postpone. If someone can briefly consider and propose next steps as a follow-up to the sprint, that'd be fine. I figure it will be easiest to propose those steps while the ETL work is fresh in people's minds.
