### ISSUE TITLE
Write script to regenerate all samples, using ocdsdata

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/sample-data#72]
Or, we can explore alternatives like exporting a sample from the hosted database.

**Comment by jpmckinney** [comment]
@robredpath Could this be discussed as part of the current sprint? It may become a follow-up rather than part of the sprint.

Related #42

**Comment by robredpath** [comment]
@jpmckinney of course - the second of the two back-to-back sprints doesn't start until Weds so we can look at priorities and scope. This doesn't seem to fit into any of the user stories that we agreed would be the scope for the sprint, though, so I'm not sure how to prioritise it. What would you consider this to be more important than in the backlog on https://github.com/orgs/open-contracting/projects/11 ?

**Comment by jpmckinney** [comment]
I wouldn't consider it more important than those. If some ways forward can be briefly explored and written as a follow-up, I think that'd be sufficient. (This might include a broader exploration of what to do with the sample-data repo, now that there is easier access to fresh data.)

**Comment by jpmckinney** [comment]
I think I'll just delete all the real examples in the meantime. Noting to save the `tools` somewhere.

**Comment by jpmckinney** [comment]
Last commit with all real-examples is https://github.com/open-contracting/sample-data/tree/8912269a5f69e279e7b81fcfc94c1146894567d3/real-examples
