### ISSUE TITLE
Decide what to do with etl-process branch

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/sample-data#75]
I don't know if the [etl-process branch](https://github.com/open-contracting/sample-data/compare/etl-process) is no longer relevant, or if there are things that should be taken forward as part of the ETL work. @robredpath @timgdavies Can you discuss and create an issue and/or delete the branch if appropriate?

**Comment by robredpath** [comment]
The branch predates the ocdsdata work by ~9 months, so it's not related to that and so I have no interest in it. @timgdavies?

**Comment by jpmckinney** [comment]
It's a few short shell scripts calling Pythons scripts and BigQuery commands, so I think safe to delete.
