### ISSUE TITLE
Delete BigQuery scripts

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/sample-data#84]
As BigQuery is no longer used or supported. 

For posterity, the last versions are at https://github.com/open-contracting/sample-data/tree/829719226e3dc4c82c9e37300f56ee0006049ec7/real-examples/tools

**Comment by robredpath** [comment]
@duncandewhurst did you use BQ for the BBC hack in the end?

**Comment by jpmckinney** [comment]
Yes, see https://crm.open-contracting.org/issues/3817#note-17

Scripts were moved to https://github.com/open-contracting/miscellaneous-private-scripts/tree/master/bigquery
